{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"machine_shape":"hm","gpuType":"A100","authorship_tag":"ABX9TyOhuDE3lrpWVbIv5gjJ/SZX"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU"},"cells":[{"cell_type":"code","source":["from google.colab import drive\n","drive.mount('/content/drive')\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"w7h-jm618ah-","executionInfo":{"status":"ok","timestamp":1714236552209,"user_tz":-330,"elapsed":30421,"user":{"displayName":"Adil Ansari","userId":"01083485150708236568"}},"outputId":"d0b37e72-3668-451b-eeb3-a3b3c99599d0"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"CXOFFAqm31cf","executionInfo":{"status":"error","timestamp":1714232285278,"user_tz":-330,"elapsed":4345950,"user":{"displayName":"Adil Ansari","userId":"01083485150708236568"}},"outputId":"620c5d5a-e451-437a-bdd3-18efcc207616"},"outputs":[{"output_type":"stream","name":"stdout","text":["Found 6874 images belonging to 4 classes.\n","Found 1717 images belonging to 4 classes.\n","Epoch 1/20\n","215/215 [==============================] - ETA: 0s - loss: 1.2799 - accuracy: 0.4228Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 2350s 11s/step - loss: 1.2799 - accuracy: 0.4228 - val_loss: 1.0953 - val_accuracy: 0.5649\n","Epoch 2/20\n","215/215 [==============================] - ETA: 0s - loss: 1.0266 - accuracy: 0.5758Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 679ms/step - loss: 1.0266 - accuracy: 0.5758 - val_loss: 0.8428 - val_accuracy: 0.6523\n","Epoch 3/20\n","215/215 [==============================] - ETA: 0s - loss: 0.8730 - accuracy: 0.6431Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 680ms/step - loss: 0.8730 - accuracy: 0.6431 - val_loss: 0.7207 - val_accuracy: 0.7321\n","Epoch 4/20\n","215/215 [==============================] - ETA: 0s - loss: 0.8103 - accuracy: 0.6686Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 678ms/step - loss: 0.8103 - accuracy: 0.6686 - val_loss: 0.6626 - val_accuracy: 0.7402\n","Epoch 5/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7922 - accuracy: 0.6801Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 145s 676ms/step - loss: 0.7922 - accuracy: 0.6801 - val_loss: 0.7919 - val_accuracy: 0.6756\n","Epoch 6/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7636 - accuracy: 0.6910Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 145s 674ms/step - loss: 0.7636 - accuracy: 0.6910 - val_loss: 0.6287 - val_accuracy: 0.7478\n","Epoch 7/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7312 - accuracy: 0.7012Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 679ms/step - loss: 0.7312 - accuracy: 0.7012 - val_loss: 0.6141 - val_accuracy: 0.7536\n","Epoch 8/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7182 - accuracy: 0.7045Warning: Underfitting likely! Validation loss higher than training loss.\n","215/215 [==============================] - 147s 684ms/step - loss: 0.7182 - accuracy: 0.7045 - val_loss: 0.7729 - val_accuracy: 0.6890\n","Epoch 9/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7170 - accuracy: 0.7104Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 679ms/step - loss: 0.7170 - accuracy: 0.7104 - val_loss: 0.6779 - val_accuracy: 0.7158\n","Epoch 10/20\n","215/215 [==============================] - ETA: 0s - loss: 0.7020 - accuracy: 0.7101Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 676ms/step - loss: 0.7020 - accuracy: 0.7101 - val_loss: 0.5754 - val_accuracy: 0.7810\n","Epoch 11/20\n","215/215 [==============================] - ETA: 0s - loss: 0.6851 - accuracy: 0.7159Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 145s 672ms/step - loss: 0.6851 - accuracy: 0.7159 - val_loss: 0.5495 - val_accuracy: 0.7723\n","Epoch 12/20\n","215/215 [==============================] - ETA: 0s - loss: 0.6735 - accuracy: 0.7300Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 680ms/step - loss: 0.6735 - accuracy: 0.7300 - val_loss: 0.6095 - val_accuracy: 0.7659\n","Epoch 13/20\n","215/215 [==============================] - ETA: 0s - loss: 0.6710 - accuracy: 0.7223Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 147s 682ms/step - loss: 0.6710 - accuracy: 0.7223 - val_loss: 0.6409 - val_accuracy: 0.7321\n","Epoch 14/20\n","215/215 [==============================] - ETA: 0s - loss: 0.6674 - accuracy: 0.7293Warning: Overfitting likely! Validation loss lower than training loss.\n","215/215 [==============================] - 146s 678ms/step - loss: 0.6674 - accuracy: 0.7293 - val_loss: 0.5588 - val_accuracy: 0.7909\n","Epoch 1/20\n"]},{"output_type":"error","ename":"ResourceExhaustedError","evalue":"Graph execution error:\n\nDetected at node model/conv5_block13_0_bn/FusedBatchNormV3 defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py\", line 37, in <module>\n\n  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py\", line 619, in start\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 685, in <lambda>\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 738, in _run_callback\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 825, in inner\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 786, in run\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 361, in process_one\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 539, in execute_request\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2975, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n\n  File \"<ipython-input-3-52580c68a342>\", line 108, in <cell line: 108>\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1150, in train_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 590, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 672, in _run_internal_graph\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 597, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 990, in _fused_batch_norm\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/control_flow_util.py\", line 108, in smart_cond\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 964, in _fused_batch_norm_training\n\nOOM when allocating tensor with shape[32,896,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv5_block13_0_bn/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_59775]","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mResourceExhaustedError\u001b[0m                    Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-52580c68a342>\u001b[0m in \u001b[0;36m<cell line: 108>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    106\u001b[0m \u001b[0mdensenet_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcreate_densenet_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    107\u001b[0m \u001b[0mdensenet_model\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moptimizer\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'adam'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mloss\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'categorical_crossentropy'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmetrics\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 108\u001b[0;31m densenet_history = densenet_model.fit(train_generator,\n\u001b[0m\u001b[1;32m    109\u001b[0m                                       \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    110\u001b[0m                                       \u001b[0mvalidation_data\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mval_generator\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     68\u001b[0m             \u001b[0;31m# To get the full stack trace, call:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m             \u001b[0;31m# `tf.debugging.disable_traceback_filtering()`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 70\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     71\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     72\u001b[0m             \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     52\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 53\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     54\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mResourceExhaustedError\u001b[0m: Graph execution error:\n\nDetected at node model/conv5_block13_0_bn/FusedBatchNormV3 defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py\", line 37, in <module>\n\n  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py\", line 619, in start\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 685, in <lambda>\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 738, in _run_callback\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 825, in inner\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 786, in run\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 361, in process_one\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 539, in execute_request\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2975, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n\n  File \"<ipython-input-3-52580c68a342>\", line 108, in <cell line: 108>\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1150, in train_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 590, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 672, in _run_internal_graph\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 597, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 990, in _fused_batch_norm\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/control_flow_util.py\", line 108, in smart_cond\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 964, in _fused_batch_norm_training\n\nOOM when allocating tensor with shape[32,896,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv5_block13_0_bn/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_59775]"]}],"source":["import os\n","import numpy as np\n","import tensorflow as tf\n","from tensorflow.keras.preprocessing.image import ImageDataGenerator\n","from tensorflow.keras.models import Sequential, Model\n","from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, GlobalAveragePooling2D\n","from tensorflow.keras.callbacks import EarlyStopping\n","from sklearn.metrics import classification_report, confusion_matrix\n","from sklearn.model_selection import GridSearchCV\n","import matplotlib.pyplot as plt\n","\n","# Define dataset folder and classes\n","dataset_folder = '/content/drive/My Drive/masked_directna'\n","classes = sorted(os.listdir(dataset_folder))\n","\n","# Load data with data augmentation\n","train_datagen = ImageDataGenerator(\n","    rescale=1./255,\n","    validation_split=0.2,\n","    rotation_range=20,\n","    width_shift_range=0.2,\n","    height_shift_range=0.2,\n","    shear_range=0.2,\n","    zoom_range=0.2,\n","    horizontal_flip=True,\n","    fill_mode='nearest'\n",")\n","\n","train_generator = train_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(512, 512),\n","    batch_size=32,\n","    class_mode='categorical',\n","    subset='training',\n","    color_mode='grayscale'\n",")\n","\n","val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)\n","\n","val_generator = val_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(512, 512),\n","    batch_size=32,\n","    class_mode='categorical',\n","    subset='validation',\n","    color_mode='grayscale'\n",")\n","\n","# Define CNN model\n","def create_cnn_model():\n","    model = Sequential([\n","        Conv2D(32, (3, 3), activation='relu', input_shape=(512, 512, 1)),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(64, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(128, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Flatten(),\n","        Dense(64, activation='relu'),\n","        Dense(len(classes), activation='softmax')\n","    ])\n","    return model\n","\n","# Define DenseNet model\n","def create_densenet_model():\n","    base_model = tf.keras.applications.DenseNet121(input_shape=(512, 512, 1),\n","                                                   include_top=False,\n","                                                   weights=None)\n","    x = GlobalAveragePooling2D()(base_model.output)\n","    x = Dense(64, activation='relu')(x)\n","    predictions = Dense(len(classes), activation='softmax')(x)\n","    model = Model(inputs=base_model.input, outputs=predictions)\n","    return model\n","\n","# Define VGG model\n","def create_vgg_model():\n","    base_model = tf.keras.applications.VGG16(input_shape=(512, 512, 1),\n","                                             include_top=False,\n","                                             weights=None)\n","    x = GlobalAveragePooling2D()(base_model.output)\n","    x = Dense(64, activation='relu')(x)\n","    predictions = Dense(len(classes), activation='softmax')(x)\n","    model = Model(inputs=base_model.input, outputs=predictions)\n","    return model\n","\n","# Early stopping callback\n","early_stopping = EarlyStopping(monitor='val_loss', patience=3)\n","\n","# Callback for monitoring underfitting and overfitting\n","class UnderfittingOverfittingCallback(tf.keras.callbacks.Callback):\n","    def on_epoch_end(self, epoch, logs=None):\n","        if logs['val_loss'] < logs['loss']:\n","            print(\"Warning: Overfitting likely! Validation loss lower than training loss.\")\n","        elif logs['val_loss'] > logs['loss']:\n","            print(\"Warning: Underfitting likely! Validation loss higher than training loss.\")\n","\n","# Compile and train CNN model\n","cnn_model = create_cnn_model()\n","cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","cnn_history = cnn_model.fit(train_generator,\n","                            epochs=20,\n","                            validation_data=val_generator,\n","                            callbacks=[early_stopping, UnderfittingOverfittingCallback()])\n","\n","# Compile and train DenseNet model\n","densenet_model = create_densenet_model()\n","densenet_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","densenet_history = densenet_model.fit(train_generator,\n","                                      epochs=20,\n","                                      validation_data=val_generator,\n","                                      callbacks=[early_stopping, UnderfittingOverfittingCallback()])\n","\n","# Compile and train VGG model\n","vgg_model = create_vgg_model()\n","vgg_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","vgg_history = vgg_model.fit(train_generator,\n","                            epochs=20,\n","                            validation_data=val_generator,\n","                            callbacks=[early_stopping, UnderfittingOverfittingCallback()])\n","\n","# Save models\n","cnn_model.save('/content/drive/My Drive/cnn_model.h5')\n","densenet_model.save('/content/drive/My Drive/densenet_model.h5')\n","vgg_model.save('/content/drive/My Drive/vgg_model.h5')\n","\n","# Ensemble\n","def ensemble(models, generator):\n","    predictions = np.zeros((generator.samples, len(classes)))\n","    for model in models:\n","        predictions += model.predict(generator)\n","    return np.argmax(predictions, axis=-1)\n","\n","models = [cnn_model, densenet_model, vgg_model]\n","\n","# Performance evaluation\n","def evaluate_ensemble(models, generator):\n","    y_true = generator.classes\n","    y_pred = ensemble(models, generator)\n","    print(\"Confusion Matrix:\")\n","    print(confusion_matrix(y_true, y_pred))\n","    print(\"\\nClassification Report:\")\n","    print(classification_report(y_true, y_pred, target_names=classes))\n","\n","print(\"Ensemble Model Evaluation:\")\n","evaluate_ensemble(models, val_generator)\n","\n","# Plotting training history\n","def plot_history(history, model_name):\n","    plt.plot(history.history['accuracy'], label='accuracy')\n","    plt.plot(history.history['val_accuracy'], label='val_accuracy')\n","    plt.plot(history.history['loss'], label='loss')\n","    plt.plot(history.history['val_loss'], label='val_loss')\n","    plt.title(f'{model_name} Training History')\n","    plt.xlabel('Epoch')\n","    plt.ylabel('Accuracy / Loss')\n","    plt.legend()\n","    plt.show()\n","\n","plot_history(cnn_history, \"CNN\")\n","plot_history(densenet_history, \"DenseNet\")\n","plot_history(vgg_history, \"VGG\")\n"]},{"cell_type":"code","source":[],"metadata":{"id":"j_f58tkK36HN"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["import os\n","import numpy as np\n","import tensorflow as tf\n","from tensorflow.keras.preprocessing.image import ImageDataGenerator\n","from tensorflow.keras.models import Sequential, Model\n","from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, GlobalAveragePooling2D\n","from tensorflow.keras.callbacks import EarlyStopping\n","from sklearn.metrics import classification_report, confusion_matrix\n","import matplotlib.pyplot as plt\n","\n","# Define dataset folder and classes\n","dataset_folder = '/content/drive/My Drive/masked_directna'\n","classes = sorted(os.listdir(dataset_folder))\n","\n","# Load data with data augmentation\n","train_datagen = ImageDataGenerator(\n","    rescale=1./255,\n","    validation_split=0.2,\n","    rotation_range=30,\n","    width_shift_range=0.2,\n","    height_shift_range=0.2,\n","    shear_range=0.2,\n","    zoom_range=0.2,\n","    horizontal_flip=True,\n","    fill_mode='nearest'\n",")\n","\n","train_generator = train_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(256, 256),\n","    batch_size=256,\n","    class_mode='categorical',\n","    subset='training',\n","    color_mode='grayscale'\n",")\n","\n","val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)\n","\n","val_generator = val_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(256, 256),\n","    batch_size=256,\n","    class_mode='categorical',\n","    subset='validation',\n","    color_mode='grayscale'\n",")\n","\n","# Early stopping callback\n","early_stopping = EarlyStopping(monitor='val_loss', patience=3)\n","\n","# Callback for monitoring underfitting and overfitting\n","class UnderfittingOverfittingCallback(tf.keras.callbacks.Callback):\n","    def on_epoch_end(self, epoch, logs=None):\n","        if logs['val_loss'] < logs['loss']:\n","            print(\"Warning: Overfitting likely! Validation loss lower than training loss.\")\n","        elif logs['val_loss'] > logs['loss']:\n","            print(\"Warning: Underfitting likely! Validation loss higher than training loss.\")\n","\n","# Learning rate schedule callback\n","def learning_rate_schedule(epoch, lr):\n","    if epoch < 5:\n","        return lr\n","    else:\n","        return lr * tf.math.exp(-0.1)\n","\n","lr_scheduler = tf.keras.callbacks.LearningRateScheduler(learning_rate_schedule)\n","\n","# Define simpler CNN model\n","def create_cnn_model():\n","    model = Sequential([\n","        Conv2D(16, (3, 3), activation='relu', input_shape=(256, 256, 1)),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(32, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(64, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Flatten(),\n","        Dense(32, activation='relu'),\n","        Dense(len(classes), activation='softmax')\n","    ])\n","    return model\n","\n","# Define simpler DenseNet model\n","def create_densenet_model():\n","    base_model = tf.keras.applications.DenseNet121(input_shape=(256, 256, 1),\n","                                                   include_top=False,\n","                                                   weights=None)\n","    x = GlobalAveragePooling2D()(base_model.output)\n","    x = Dense(32, activation='relu')(x)\n","    predictions = Dense(len(classes), activation='softmax')(x)\n","    model = Model(inputs=base_model.input, outputs=predictions)\n","    return model\n","\n","# Define simpler VGG model\n","def create_vgg_model():\n","    base_model = tf.keras.applications.VGG16(input_shape=(256, 256, 1),\n","                                             include_top=False,\n","                                             weights=None)\n","    x = GlobalAveragePooling2D()(base_model.output)\n","    x = Dense(32, activation='relu')(x)\n","    predictions = Dense(len(classes), activation='softmax')(x)\n","    model = Model(inputs=base_model.input, outputs=predictions)\n","    return model\n","\n","# Compile and train CNN model\n","cnn_model = create_cnn_model()\n","cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","cnn_history = cnn_model.fit(train_generator,\n","                            epochs=20,\n","                            validation_data=val_generator,\n","                            callbacks=[early_stopping, UnderfittingOverfittingCallback(), lr_scheduler])\n","\n","# Compile and train DenseNet model\n","densenet_model = create_densenet_model()\n","densenet_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","densenet_history = densenet_model.fit(train_generator,\n","                                      epochs=20,\n","                                      validation_data=val_generator,\n","                                      callbacks=[early_stopping, UnderfittingOverfittingCallback(), lr_scheduler])\n","\n","# Compile and train VGG model\n","vgg_model = create_vgg_model()\n","vgg_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","vgg_history = vgg_model.fit(train_generator,\n","                            epochs=20,\n","                            validation_data=val_generator,\n","                            callbacks=[early_stopping, UnderfittingOverfittingCallback(), lr_scheduler])\n","\n","# Save models\n","cnn_model.save('/content/drive/My Drive/cnn_model.h5')\n","densenet_model.save('/content/drive/My Drive/densenet_model.h5')\n","vgg_model.save('/content/drive/My Drive/vgg_model.h5')\n","\n","# Ensemble\n","def ensemble(models, generator):\n","    predictions = np.zeros((generator.samples, len(classes)))\n","    for model in models:\n","        predictions += model.predict(generator)\n","    return np.argmax(predictions, axis=-1)\n","\n","models = [cnn_model, densenet_model, vgg_model]\n","\n","# Performance evaluation\n","def evaluate_ensemble(models, generator):\n","    y_true = generator.classes\n","    y_pred = ensemble(models, generator)\n","    print(\"Confusion Matrix:\")\n","    print(confusion_matrix(y_true, y_pred))\n","    print(\"\\nClassification Report:\")\n","    print(classification_report(y_true, y_pred, target_names=classes))\n","\n","print(\"Ensemble Model Evaluation:\")\n","evaluate_ensemble(models, val_generator)\n","\n","# Plotting training history\n","def plot_history(history, model_name):\n","    plt.plot(history.history['accuracy'], label='accuracy')\n","    plt.plot(history.history['val_accuracy'], label='val_accuracy')\n","    plt.plot(history.history['loss'], label='loss')\n","    plt.plot(history.history['val_loss'], label='val_loss')\n","    plt.title(f'{model_name} Training History')\n","    plt.xlabel('Epoch')\n","    plt.ylabel('Accuracy / Loss')\n","    plt.legend()\n","    plt.show()\n","\n","plot_history(cnn_history, \"CNN\")\n","plot_history(densenet_history, \"DenseNet\")\n","plot_history(vgg_history, \"VGG\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"udwz4XzLck-k","executionInfo":{"status":"error","timestamp":1714241610636,"user_tz":-330,"elapsed":4861823,"user":{"displayName":"Adil Ansari","userId":"01083485150708236568"}},"outputId":"b45d2158-7dd8-4e30-adbe-416c4f6d62de"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Found 6874 images belonging to 4 classes.\n","Found 1717 images belonging to 4 classes.\n","Epoch 1/20\n","27/27 [==============================] - ETA: 0s - loss: 1.2654 - accuracy: 0.4508  Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 3533s 132s/step - loss: 1.2654 - accuracy: 0.4508 - val_loss: 1.2157 - val_accuracy: 0.4799 - lr: 0.0010\n","Epoch 2/20\n","27/27 [==============================] - ETA: 0s - loss: 1.1237 - accuracy: 0.5445Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 1.1237 - accuracy: 0.5445 - val_loss: 1.1193 - val_accuracy: 0.5341 - lr: 0.0010\n","Epoch 3/20\n","27/27 [==============================] - ETA: 0s - loss: 1.0563 - accuracy: 0.5620Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 1.0563 - accuracy: 0.5620 - val_loss: 0.9375 - val_accuracy: 0.5923 - lr: 0.0010\n","Epoch 4/20\n","27/27 [==============================] - ETA: 0s - loss: 1.0434 - accuracy: 0.5630Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 1.0434 - accuracy: 0.5630 - val_loss: 0.8954 - val_accuracy: 0.6430 - lr: 0.0010\n","Epoch 5/20\n","27/27 [==============================] - ETA: 0s - loss: 0.9518 - accuracy: 0.6104Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 0.9518 - accuracy: 0.6104 - val_loss: 0.8531 - val_accuracy: 0.6517 - lr: 0.0010\n","Epoch 6/20\n","27/27 [==============================] - ETA: 0s - loss: 0.9208 - accuracy: 0.6276Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.9208 - accuracy: 0.6276 - val_loss: 0.8143 - val_accuracy: 0.6797 - lr: 9.0484e-04\n","Epoch 7/20\n","27/27 [==============================] - ETA: 0s - loss: 0.8639 - accuracy: 0.6552Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 62s 2s/step - loss: 0.8639 - accuracy: 0.6552 - val_loss: 0.7362 - val_accuracy: 0.7199 - lr: 8.1873e-04\n","Epoch 8/20\n","27/27 [==============================] - ETA: 0s - loss: 0.8507 - accuracy: 0.6536Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.8507 - accuracy: 0.6536 - val_loss: 0.7108 - val_accuracy: 0.7210 - lr: 7.4082e-04\n","Epoch 9/20\n","27/27 [==============================] - ETA: 0s - loss: 0.8214 - accuracy: 0.6692Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.8214 - accuracy: 0.6692 - val_loss: 0.6849 - val_accuracy: 0.7467 - lr: 6.7032e-04\n","Epoch 10/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7985 - accuracy: 0.6776Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7985 - accuracy: 0.6776 - val_loss: 0.6846 - val_accuracy: 0.7484 - lr: 6.0653e-04\n","Epoch 11/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7740 - accuracy: 0.6923Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7740 - accuracy: 0.6923 - val_loss: 0.6401 - val_accuracy: 0.7542 - lr: 5.4881e-04\n","Epoch 12/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7703 - accuracy: 0.6896Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7703 - accuracy: 0.6896 - val_loss: 0.6240 - val_accuracy: 0.7688 - lr: 4.9659e-04\n","Epoch 13/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7539 - accuracy: 0.6960Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 0.7539 - accuracy: 0.6960 - val_loss: 0.6162 - val_accuracy: 0.7688 - lr: 4.4933e-04\n","Epoch 14/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7708 - accuracy: 0.6893Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7708 - accuracy: 0.6893 - val_loss: 0.6107 - val_accuracy: 0.7764 - lr: 4.0657e-04\n","Epoch 15/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7417 - accuracy: 0.7074Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 0.7417 - accuracy: 0.7074 - val_loss: 0.6149 - val_accuracy: 0.7647 - lr: 3.6788e-04\n","Epoch 16/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7340 - accuracy: 0.7002Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 0.7340 - accuracy: 0.7002 - val_loss: 0.6056 - val_accuracy: 0.7676 - lr: 3.3287e-04\n","Epoch 17/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7250 - accuracy: 0.7096Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7250 - accuracy: 0.7096 - val_loss: 0.6082 - val_accuracy: 0.7653 - lr: 3.0119e-04\n","Epoch 18/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7290 - accuracy: 0.7037Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7290 - accuracy: 0.7037 - val_loss: 0.5924 - val_accuracy: 0.7828 - lr: 2.7253e-04\n","Epoch 19/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7259 - accuracy: 0.7101Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 61s 2s/step - loss: 0.7259 - accuracy: 0.7101 - val_loss: 0.6003 - val_accuracy: 0.7729 - lr: 2.4660e-04\n","Epoch 20/20\n","27/27 [==============================] - ETA: 0s - loss: 0.7149 - accuracy: 0.7130Warning: Overfitting likely! Validation loss lower than training loss.\n","27/27 [==============================] - 60s 2s/step - loss: 0.7149 - accuracy: 0.7130 - val_loss: 0.5964 - val_accuracy: 0.7729 - lr: 2.2313e-04\n","Epoch 1/20\n"]},{"output_type":"error","ename":"ResourceExhaustedError","evalue":"Graph execution error:\n\nDetected at node model/conv4_block23_0_bn/FusedBatchNormV3 defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py\", line 37, in <module>\n\n  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py\", line 619, in start\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 685, in <lambda>\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 738, in _run_callback\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 825, in inner\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 786, in run\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 361, in process_one\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 539, in execute_request\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2975, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n\n  File \"<ipython-input-1-f907d6a7937f>\", line 116, in <cell line: 116>\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1150, in train_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 590, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 672, in _run_internal_graph\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 597, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 990, in _fused_batch_norm\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/control_flow_util.py\", line 108, in smart_cond\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 964, in _fused_batch_norm_training\n\nOOM when allocating tensor with shape[256,960,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv4_block23_0_bn/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_47786]","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mResourceExhaustedError\u001b[0m                    Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-f907d6a7937f>\u001b[0m in \u001b[0;36m<cell line: 116>\u001b[0;34m()\u001b[0m\n\u001b[1;32m    114\u001b[0m \u001b[0mdensenet_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcreate_densenet_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    115\u001b[0m \u001b[0mdensenet_model\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moptimizer\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'adam'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mloss\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'categorical_crossentropy'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmetrics\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 116\u001b[0;31m densenet_history = densenet_model.fit(train_generator,\n\u001b[0m\u001b[1;32m    117\u001b[0m                                       \u001b[0mepochs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    118\u001b[0m                                       \u001b[0mvalidation_data\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mval_generator\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     68\u001b[0m             \u001b[0;31m# To get the full stack trace, call:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m             \u001b[0;31m# `tf.debugging.disable_traceback_filtering()`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 70\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     71\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     72\u001b[0m             \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     52\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 53\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     54\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mResourceExhaustedError\u001b[0m: Graph execution error:\n\nDetected at node model/conv4_block23_0_bn/FusedBatchNormV3 defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py\", line 37, in <module>\n\n  File \"/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py\", line 619, in start\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 685, in <lambda>\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py\", line 738, in _run_callback\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 825, in inner\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 786, in run\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 361, in process_one\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 261, in dispatch_shell\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py\", line 539, in execute_request\n\n  File \"/usr/local/lib/python3.10/dist-packages/tornado/gen.py\", line 234, in wrapper\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py\", line 302, in do_execute\n\n  File \"/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py\", line 539, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2975, in run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n\n  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n\n  File \"<ipython-input-1-f907d6a7937f>\", line 116, in <cell line: 116>\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 1150, in train_step\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py\", line 590, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 515, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py\", line 672, in _run_internal_graph\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py\", line 1149, in __call__\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py\", line 96, in error_handler\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 597, in call\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 990, in _fused_batch_norm\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/utils/control_flow_util.py\", line 108, in smart_cond\n\n  File \"/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/batch_normalization.py\", line 964, in _fused_batch_norm_training\n\nOOM when allocating tensor with shape[256,960,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv4_block23_0_bn/FusedBatchNormV3}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_47786]"]}]},{"cell_type":"code","source":["import os\n","import numpy as np\n","import tensorflow as tf\n","from tensorflow.keras.preprocessing.image import ImageDataGenerator\n","from tensorflow.keras.models import Sequential\n","from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout\n","from tensorflow.keras.callbacks import EarlyStopping\n","from tensorflow.keras import regularizers\n","from sklearn.metrics import classification_report, confusion_matrix\n","import matplotlib.pyplot as plt\n","\n","# Define dataset folder and classes\n","dataset_folder = '/content/drive/My Drive/masked_direct'\n","classes = sorted(os.listdir(dataset_folder))\n","\n","# Load data with data augmentation\n","train_datagen = ImageDataGenerator(\n","    rescale=1./255,\n","    validation_split=0.2,\n","    rotation_range=30,\n","    width_shift_range=0.2,\n","    height_shift_range=0.2,\n","    shear_range=0.2,\n","    zoom_range=0.2,\n","    horizontal_flip=True,\n","    fill_mode='nearest'\n",")\n","\n","train_generator = train_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(512, 512),  # Adjusted target size\n","    color_mode='grayscale',  # Set color mode to grayscale\n","    batch_size=32,\n","    class_mode='categorical',\n","    subset='training'\n",")\n","\n","val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)\n","\n","val_generator = val_datagen.flow_from_directory(\n","    dataset_folder,\n","    target_size=(512, 512),  # Adjusted target size\n","    color_mode='grayscale',  # Set color mode to grayscale\n","    batch_size=32,\n","    class_mode='categorical',\n","    subset='validation'\n",")\n","\n","# Define CNN model\n","def create_cnn_model(input_shape, num_classes):\n","    model = Sequential([\n","        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(64, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Conv2D(128, (3, 3), activation='relu'),\n","        MaxPooling2D((2, 2)),\n","        Flatten(),\n","        Dense(128, activation='relu'),\n","        Dropout(0.5),\n","        Dense(num_classes, activation='softmax', kernel_regularizer=regularizers.l2(0.001))\n","    ])\n","    return model\n","\n","# Create and compile the model\n","input_shape = (512, 512, 1)  # Adjusted input shape for grayscale images\n","num_classes = len(classes)\n","\n","cnn_model = create_cnn_model(input_shape, num_classes)\n","cnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n","\n","# Early stopping callback\n","early_stopping = EarlyStopping(monitor='val_loss', patience=3)\n","\n","# Train the model\n","history = cnn_model.fit(\n","    train_generator,\n","    epochs=25,\n","    validation_data=val_generator,\n","    callbacks=[early_stopping]\n",")\n","\n","# Evaluate the model\n","val_loss, val_acc = cnn_model.evaluate(val_generator)\n","print(\"Validation Loss:\", val_loss)\n","print(\"Validation Accuracy:\", val_acc)\n","\n","# Save the model\n","cnn_model.save('/content/drive/My Drive/cnn_model.h5')\n","\n","# Plot training history\n","def plot_history(history):\n","    plt.plot(history.history['accuracy'], label='accuracy')\n","    plt.plot(history.history['val_accuracy'], label='val_accuracy')\n","    plt.plot(history.history['loss'], label='loss')\n","    plt.plot(history.history['val_loss'], label='val_loss')\n","    plt.title('Model Training History')\n","    plt.xlabel('Epoch')\n","    plt.ylabel('Metric')\n","    plt.legend()\n","    plt.show()\n","\n","plot_history(history)\n","\n","# Performance evaluation\n","def evaluate_model(model, generator):\n","    y_true = generator.classes\n","    y_pred = np.argmax(model.predict(generator), axis=-1)\n","    print(\"Confusion Matrix:\")\n","    print(confusion_matrix(y_true, y_pred))\n","    print(\"\\nClassification Report:\")\n","    print(classification_report(y_true, y_pred, target_names=classes))\n","\n","print(\"Model Evaluation:\")\n","evaluate_model(cnn_model, val_generator)\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"t9LaJirVdhQR","outputId":"5f54945c-3bb0-4c76-feb2-c61051be304a"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Found 3851 images belonging to 4 classes.\n","Found 961 images belonging to 4 classes.\n","Epoch 1/25\n"," 64/121 [==============>...............] - ETA: 13:55 - loss: 1.4056 - accuracy: 0.2715"]}]},{"cell_type":"code","source":[],"metadata":{"id":"MMdhVeyuyL_M"},"execution_count":null,"outputs":[]}]}